spring.application.name=api-gateway
server.port=${PORT:10000}
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]

# Disable auto-discovery based routing
spring.cloud.gateway.mvc.discovery.locator.enabled=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Eureka configuration
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Custom route to user-service
spring.cloud.gateway.mvc.routes[0].id=userservice
spring.cloud.gateway.mvc.routes[0].uri=lb://userservice
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/users/**

# Custom route to train-service
spring.cloud.gateway.mvc.routes[1].id=trainservice
spring.cloud.gateway.mvc.routes[1].uri=lb://trainservice
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/trains/**

# Custom route to reservation-service
spring.cloud.gateway.mvc.routes[2].id=reservationservice
spring.cloud.gateway.mvc.routes[2].uri=lb://reservationservice
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/reservations/**

# Custom route to payment-service
spring.cloud.gateway.mvc.routes[3].id=paymentservice
spring.cloud.gateway.mvc.routes[3].uri=lb://paymentservice
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/payments/**

# Custom route to reservation-service trip APIs
spring.cloud.gateway.mvc.routes[4].id=tripservice
spring.cloud.gateway.mvc.routes[4].uri=lb://reservationservice
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/v1/trips/**
