server.port=${PORT:10000}

# Stripe Secret Key
stripe.secretKey=${STRIPE_SECRET_KEY}

spring.datasource.url=${PAYMENTSERVICE_DB_URL}
spring.datasource.username=${PAYMENTSERVICE_DB_USERNAME:${DB_USERNAME}}
spring.datasource.password=${PAYMENTSERVICE_DB_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Payment Gateway Configuration
payment.gateway=${PAYMENT_GATEWAY:mock}
payment.success-url=${PAYMENT_SUCCESS_URL:http://localhost:5173/payment-success}
payment.cancel-url=${PAYMENT_CANCEL_URL:http://localhost:5173/dashboard}

# Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
spring.mail.test-connection=${MAIL_TEST_CONNECTION:false}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration