server.port=${PORT:8083}

# Database Configuration
spring.datasource.url=${RESERVATIONSERVICE_DB_URL:jdbc:mysql://localhost:3306/reservationservicetrain?createDatabaseIfNotExist=true}
spring.datasource.username=${RESERVATIONSERVICE_DB_USERNAME:${DB_USERNAME:root}}
spring.datasource.password=${RESERVATIONSERVICE_DB_PASSWORD:${DB_PASSWORD:Vaishna15}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5

# Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
