server.port=${PORT:10000}

spring.datasource.url=${TRAINSERVICE_DB_URL}
spring.datasource.username=${TRAINSERVICE_DB_USERNAME:${DB_USERNAME}}
spring.datasource.password=${TRAINSERVICE_DB_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
