spring.application.name=config-server
server.port=${PORT:8888}
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]

spring.cloud.config.server.native.search-locations=${CONFIG_REPOSITORY_LOCATION:file:../config-repository}
spring.profiles.active=native