spring.application.name=eureka-server
server.port=${PORT:8761}
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.cloud.config.import-check.enabled=false